import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { motion, useScroll, useTransform } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, Download, Mail, Menu, Moon, MoveRight, Play, Send, Sun, X } from 'lucide-react'
import './styles.css'

const projects = [
  { title: 'School System Processing', type: 'Web / System', tag: 'Education', image: '/images/schoolsystem.png', prototypeUrl: 'https://www.figma.com/proto/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=666-3039&t=FSTyGdcp2NDf3sWv-1&scaling=scale-down&content-scaling=fixed&page-id=530%3A6591&starting-point-node-id=666%3A3039' },
  { title: 'Parent School App', type: 'Mobile App', tag: 'Education', image: '/images/school_project.png', prototypeUrl: 'https://www.figma.com/design/WYJRe4u1yD0aLy3iKj1lNa/Parent-App?node-id=0-1&t=pjhIp33RZyL8laua-1', caseStudyUrl: 'https://www.figma.com/design/WYJRe4u1yD0aLy3iKj1lNa/Parent-App?node-id=0-1&t=pjhIp33RZyL8laua-1' },
  { title: 'Loan App', type: 'Mobile App', tag: 'Fintech', image: '/images/loan_projectc.png', prototypeUrl: 'https://www.figma.com/proto/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=1945-26004&t=CXMgWvBoPHy1uGVy-1&scaling=scale-down&content-scaling=fixed&page-id=1945%3A4869&starting-point-node-id=1945%3A26004&show-proto-sidebar=1', caseStudyUrl: 'https://www.figma.com/design/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=1666-4869&t=nYWLUl63MtjR8mSG-1' },
  { title: 'POS App', type: 'Mobile + Web', tag: 'Retail', image: '/images/POS_project.png', prototypeUrl: 'https://www.figma.com/proto/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=1787-13976&t=ZFE1jF6vg4S1jVc6-1&scaling=scale-down&content-scaling=fixed&page-id=1784%3A8363&starting-point-node-id=1787%3A13976&show-proto-sidebar=1', caseStudyUrl: 'https://www.figma.com/design/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=1784-8363&t=nYWLUl63MtjR8mSG-1' },
  { title: 'Delivery App', type: 'Mobile App', tag: 'Delivery', image: '/images/delivery.png', prototypeUrl: 'https://www.figma.com/design/p5hjXQGPrAwHgfRMi0FyId/delivery?node-id=487-2665&t=KPRoTyHkqqAmoL1o-1', caseStudyUrl: 'https://www.figma.com/design/p5hjXQGPrAwHgfRMi0FyId/delivery?node-id=487-2665&t=KPRoTyHkqqAmoL1o-1' },
  { title: 'Service Maintenance App', type: 'Mobile App', tag: 'Service', image: '/images/servicemainternance_project.png', prototypeUrl: 'https://www.figma.com/proto/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=2331-44212&p=f&t=l16uY2BwOgK75lA6-1&scaling=scale-down&content-scaling=fixed&page-id=2311%3A13097&starting-point-node-id=2321%3A44192&show-proto-sidebar=1', caseStudyUrl: 'https://www.figma.com/design/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=2311-13097&t=nYWLUl63MtjR8mSG-1' },
  { title: 'Ecommerce App', type: 'Mobile App', tag: 'Ecommerce', image: '/images/ecommerce_project.png', prototypeUrl: 'https://www.figma.com/proto/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=218-6513&p=f&t=4iq5JGLs9LepY0aO-1&scaling=scale-down&content-scaling=fixed&page-id=218%3A5918&starting-point-node-id=218%3A6513&show-proto-sidebar=1', caseStudyUrl: 'https://www.figma.com/design/d0q9M4DOgkFrlT78VQtngW/My-Project?node-id=218-5918&t=nYWLUl63MtjR8mSG-1' },
  { title: 'Rice App', type: 'Mobile App', tag: 'Business', image: '/images/rice_project.png', prototypeUrl: 'https://www.figma.com/design/TyibH4pWXNWPPv4SAqO4Qj/POS-Rice?node-id=305-613&t=pjhIp33RZyL8laua-1', caseStudyUrl: 'https://www.figma.com/design/TyibH4pWXNWPPv4SAqO4Qj/POS-Rice?node-id=305-613&t=pjhIp33RZyL8laua-1' },
  { title: 'Travel and Trip Tide App', type: 'Mobile App', tag: 'Travel', image: '/images/tripbooking_project.png', prototypeUrl: 'https://www.figma.com/design/DAl1Tkak7M7qa2jhWilOK4/Final?node-id=0-1&t=6ZYYIHxjq70JhNJs-1', caseStudyUrl: 'https://www.figma.com/design/DAl1Tkak7M7qa2jhWilOK4/Final?node-id=0-1&t=6ZYYIHxjq70JhNJs-1' },
]
const gridProjects = projects.slice(1)
const caseStudies = ['School System Processing', 'Service Maintenance App', 'Loan App', 'Ecommerce App'].map(t => projects.find(p => p.title === t))

const skills = ['Figma', 'Adobe XD', 'Photoshop', 'Video Editor', 'Wireframing', 'Prototyping', 'User Flow', 'Design Systems', 'HTML', 'CSS', 'JavaScript', 'React', 'Laravel', 'Flutter']
const process = ['Research', 'User Flow', 'Wireframe', 'UI Design', 'Prototype', 'Test', 'Improve']
const liveApps = [
  { name: 'TTC Mobile', category: 'Loan Management App', tone: 'blue', initials: 'TTC', logo: '/images/TTC_logo.png', description: 'A focused loan management experience that helps customers apply, track repayments, and understand their account with confidence.', points: ['Designed a clear application and repayment journey.', 'Created simple loan status and payment experiences.', 'Prepared production-ready mobile UI and prototypes.'], tags: ['UX/UI Design', 'User Flow', 'Mobile App', 'Prototype'], stores: [{ label: 'App Store', url: 'https://apps.apple.com/us/app/ttc-mobile/id6787681800' }, { label: 'Google Play', url: 'https://play.google.com/store/apps/details?id=com.kh.ttcloan2&pcampaignid=web_share' }] },
  { name: 'IIS School', category: 'School Management App', tone: 'green', initials: 'IIS', logo: '/images/IIS_Logo.png', description: 'A school management app that brings classes, schedules, communication, and daily school tasks into one clear experience.', points: ['Mapped key flows for students, parents, and staff.', 'Designed an accessible information hierarchy for daily use.', 'Built reusable patterns for a consistent mobile product.'], tags: ['UX/UI Design', 'Mobile App', 'Design System', 'Figma'], stores: [{ label: 'App Store', url: 'https://apps.apple.com/us/app/ideally-international-school/id6791925974' }, { label: 'Google Play', url: 'https://play.google.com/store/apps/details?id=com.kh.iisschool&pcampaignid=web_share' }] },
  { name: 'MuMu Delivery', category: 'Delivery App', tone: 'yellow', initials: 'M', logo: '/images/MuMu_Logo .png', iconFill: true, description: 'A delivery workflow designed for speed, helping drivers manage orders, routes, and delivery status from the road.', points: ['Simplified the order-to-delivery flow for drivers.', 'Designed scannable screens for fast decisions in motion.', 'Prototyped status, tracking, and delivery confirmation states.'], tags: ['UX/UI Design', 'Driver App', 'User Flow', 'Prototype'], stores: [{ label: 'Google Play', url: 'https://play.google.com/store/apps/details?id=com.kh.mumudriver&pcampaignid=web_share' }, { label: 'App Store', url: 'https://apps.apple.com/us/app/mumu-driver/id6796636426' }] },
  { name: 'ATB HUB', category: 'Delivery App', tone: 'teal', initials: 'ATB', logo: '/images/ATB_Logo.png', description: 'A delivery application for Angkor Thom Book Center, covering booking, live delivery tracking, and barcode scanning with validation.', points: ['Designed booking, delivery tracking, and barcode scanning flows.', 'Created a scalable mobile UI kit and developer-ready handoff.', 'Worked with the team through testing, release, and iteration.'], tags: ['UX/UI Design', 'Mobile App', 'Design System', 'Figma'], stores: [{ label: 'Google Play', url: 'https://play.google.com/store/apps/details?id=com.kh.angkorthom&pcampaignid=web_share' }, { label: 'App Store', url: 'https://apps.apple.com/us/app/atb-hub/id6791481393' }] },
  { name: 'CIAC School', category: 'School Management App', tone: 'red', initials: 'CIAC', logo: '/images/CIAC_Logo.png', description: 'A structured school companion that makes academic information and everyday communication easier to find and use.', points: ['Organized complex school information into clear flows.', 'Designed simple navigation for multiple user roles.', 'Created responsive UI patterns ready for development.'], tags: ['UX/UI Design', 'Mobile App', 'Information Architecture', 'Figma'], stores: [{ label: 'Google Play', url: 'https://play.google.com/store/apps/details?id=com.kh.ciacschool&pcampaignid=web_share' }, { label: 'App Store', url: 'https://apps.apple.com/us/app/ciac-school/id6777597959' }] },
  { name: 'One Express', category: 'Express Delivery App', tone: 'pink', initials: '1X', logo: '/images/One_Express_Logo.png', description: 'An express delivery experience focused on clear order progress, dependable handoff, and efficient customer updates.', points: ['Designed a straightforward delivery tracking journey.', 'Clarified key order states and customer actions.', 'Delivered mobile UI concepts for a fast, practical experience.'], tags: ['UX/UI Design', 'Delivery App', 'Mobile UI', 'Prototype'], stores: [{ label: 'App Store', url: 'https://apps.apple.com/us/app/1one-express/id6793854034' }, { label: 'Google Play', url: 'https://play.google.com/store/apps/details?id=com.kh.oneexpress&pcampaignid=web_share' }] },
]
function Mockup({ project, large = false }) {
  return <div className={`mockup ${large ? 'large' : ''}`}>
    <img src={project.image} alt={project.title} loading="lazy" />
  </div>
}

function App() {
  const [menu, setMenu] = useState(false)
  const [theme, setTheme] = useState(() => document.documentElement.getAttribute('data-theme') || 'light')
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
    try { localStorage.setItem('theme', theme) } catch (e) {}
  }, [theme])
  const toggleTheme = () => setTheme(t => t === 'dark' ? 'light' : 'dark')
  const { scrollY } = useScroll()
  const floatY = useTransform(scrollY, [0, 600], [0, 110])
  const fadeUp = { hidden: { opacity: 0, y: 25 }, show: { opacity: 1, y: 0, transition: { duration: .65 } } }
  return <main>
    <nav><a className="logo" href="#top">Rin LyHour<span>.</span></a><div className="navlinks"><a href="#about">About</a><a href="#work">Work</a><a href="#process">Process</a></div><div style={{display:'flex',alignItems:'center',gap:18}}><a className="navcontact" href="#contact">Let’s talk <ArrowUpRight size={16}/></a><button className="theme-toggle nav-theme-toggle" aria-label="Toggle theme" onClick={toggleTheme}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button><button className="menubtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav>
    {menu && <div className="mobilemenu"><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#work" onClick={()=>setMenu(false)}>Work</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a><button className="theme-toggle" aria-label="Toggle theme" onClick={toggleTheme}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button></div>}
    <section id="top" className="hero gridbg">
      <motion.div className="hero-copy" initial="hidden" animate="show" variants={{show:{transition:{staggerChildren:.12}}}}><motion.p variants={fadeUp} className="eyebrow"><i></i> AVAILABLE FOR SELECT PROJECTS</motion.p><motion.h1 variants={fadeUp}>I turn complex ideas into <span>simple</span> digital experiences.</motion.h1><motion.p variants={fadeUp} className="intro">I’m <b>Rin LyHour</b>, a UI/UX designer shaping useful, intuitive products for people and businesses.</motion.p><motion.div variants={fadeUp} className="hero-actions"><a className="button dark" href="#work">View projects <ArrowDownRight size={18}/></a><a className="textbutton" href="#contact"><Download size={17}/> Download CV</a></motion.div></motion.div>
      <motion.div className="hero-art" style={{y:floatY}}><div className="orbit orbit1"></div><div className="orbit orbit2"></div><div className="hero-card"><span className="cardlabel">DESIGNER / DEVELOPER</span><div className="portrait"><img src="/images/Profile.png" alt="Rin LyHour"/><div className="face">R</div></div><div className="signature">Rin LyHour</div><div className="cardbottom"><span>UI/UX DESIGN</span><span>2025 — ∞</span></div></div><div className="dot dot1"></div><div className="dot dot2"></div></motion.div>
      <div className="scrollnote">SCROLL TO EXPLORE <span>↓</span></div>
    </section>
    <section id="about" className="about section"><motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fadeUp}><p className="eyebrow"><i></i> 01 / ABOUT ME</p><h2>Designing with clarity,<br/>purpose &amp; <i>curiosity.</i></h2></motion.div><motion.div className="about-copy" initial="hidden" whileInView="show" viewport={{once:true}} variants={fadeUp}><p>I’m a fourth-year Bachelor’s student and a UI/UX Designer with hands-on experience creating thoughtful digital products.</p><p>Since 2025, I’ve been working at <b>Softcreative</b>, where I design web platforms, mobile apps, and software systems that make work feel easier.</p><a href="#contact" className="arrowlink">More about me <ArrowUpRight size={18}/></a></motion.div><div className="facts"><div><b>01+</b><span>Years of experience</span></div><div><b>10+</b><span>Featured UX/UI projects</span></div><div><b>2025</b><span>Joined Softcreative</span></div></div></section>
    <section className="experience"><div className="section"><p className="eyebrow"><i></i> 02 / EXPERIENCE</p><div className="exp-head"><h2>Making ideas<br/>work <i>better.</i></h2><p>I care about the details that make a product not just look good, but work beautifully in the real world.</p></div><div className="experience-card"><div><span className="jobnum">01</span><h3>Softcreative</h3><p>UI/UX Designer · March 2025 — Present</p></div><div className="duties">{['UI/UX Design','Web & Mobile Application Design','Software System Design','Client & Business Requirements','Prototype & User Flow','Collaboration with Developers'].map(x=><span key={x}><Check size={14}/>{x}</span>)}</div><ArrowUpRight className="exp-arrow"/></div></div></section>
    <section id="work" className="work section"><div className="work-title"><div><p className="eyebrow"><i></i> 03 / SELECTED WORK</p><h2>Featured <i>projects.</i></h2></div><p>From first idea to final interaction — a selection of systems designed to solve meaningful problems.</p></div><div className="projects">{gridProjects.map((p,i)=><motion.article className={`project project-${i}`} key={p.title} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}} whileHover={{y:-8}}><div className="project-top"><span>{String(i+1).padStart(2,'0')} — {p.tag}</span><a aria-label="View case study" href={p.caseStudyUrl || '#'} target={p.caseStudyUrl ? '_blank' : undefined} rel="noreferrer"><ArrowUpRight size={20}/></a></div><div className="project-mock"><Mockup project={p}/></div><div className="project-foot"><div><h3>{p.title}</h3><p>{p.type} · UX/UI Design</p></div><a className="view" href={p.caseStudyUrl || '#'} target={p.caseStudyUrl ? '_blank' : undefined} rel="noreferrer">View case study <ChevronRight size={16}/></a></div></motion.article>)}</div></section>
    <section className="live-apps section"><div className="live-heading"><div><p className="eyebrow"><i></i> 04 / LIVE APP EXPERIENCES</p><h2>Apps I designed<br/>and <i>shipped.</i></h2></div><p>Mobile experiences I designed with product and developer teams — delivered for release on Google Play and the App Store.</p></div><div className="live-list">{liveApps.map((app, i) => <motion.article className="live-card" key={app.name} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}}><div className={`app-visual ${app.tone}`}><div className={`app-icon${app.iconFill ? ' fill' : ''}`}>{app.logo ? <img src={app.logo} alt={app.name} loading="lazy"/> : app.initials}</div><div className="phone"><div className="phone-top"></div><div className="phone-screen"><small>{app.name}</small><b>Welcome back</b><div></div><div></div><div></div></div></div></div><div className="live-content"><p className="live-meta"><b>✓ UX/UI BY ME</b><span>·</span>{app.category}</p><h3>{app.name}</h3><p className="live-description">{app.description}</p><ul className="live-points">{app.points.map(point => <li key={point}><Check size={14}/>{point}</li>)}</ul><div className="app-tags">{app.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="store-links">{app.stores.map(store => <a key={store.label} href={store.url} target="_blank" rel="noreferrer"><span className={store.label === 'App Store' ? 'applemark' : 'playmark'}>{store.label === 'App Store' ? '●' : '▶'}</span> {store.label} <ArrowUpRight size={15}/></a>)}</div></div></motion.article>)}</div></section>
    <section className="case-study"><div className="section"><div className="case-header"><p className="eyebrow"><i></i> 05 / CASE STUDY</p><span>INTERACTIVE PREVIEW</span></div>{caseStudies.map((cs,i)=><div className="case-block" key={cs.title}><div className="casegrid"><div className="casecopy"><p className="case-index">{String(i+1).padStart(2,'0')} — {cs.tag.toUpperCase()}</p><h2>{cs.title}</h2><p>A product experience built around clear workflows, confident decisions, and a system that can scale with the business.</p><a className="button lime" href={cs.prototypeUrl || '#'} target={cs.prototypeUrl ? '_blank' : undefined} rel="noreferrer"><Play size={15} fill="currentColor"/> View prototype</a></div><motion.div initial={{opacity:0,scale:.94}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} className="casevisual"><Mockup project={cs} large/><div className="floating-tag">Live<br/><b>Prototype</b></div></motion.div></div><div className="casesteps">{['Problem','Goal','Research','User Flow','Wireframe','UI Design','Prototype','Development','Final Result'].map((step,j)=><div key={step}><span>0{j+1}</span>{step}</div>)}</div></div>)}</div></section>
    <section id="process" className="process section"><p className="eyebrow"><i></i> 06 / HOW I WORK</p><h2>A process that keeps<br/>people at the <i>center.</i></h2><div className="process-line">{process.map((x,i)=><React.Fragment key={x}><motion.div whileHover={{scale:1.08}}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b></motion.div>{i<process.length-1 && <em>→</em>}</React.Fragment>)}</div></section>
    <section className="skills section"><div><p className="eyebrow"><i></i> 07 / TOOLKIT</p><h2>Tools I use to<br/>bring ideas <i>alive.</i></h2></div><div className="skill-list">{skills.map((s,i)=><motion.div key={s} whileHover={{x:8}}><span>{String(i+1).padStart(2,'0')}</span><b>{s}</b><ArrowUpRight size={18}/></motion.div>)}</div></section>
    <footer id="contact"><div className="footer-top"><p className="eyebrow"><i></i> 08 / GET IN TOUCH</p><h2>Let’s create something<br/><i>meaningful</i> together.</h2><a className="round-link" href="https://t.me/LyyHourRinn" target="_blank" rel="noreferrer"><MoveRight size={34}/></a></div><div className="footer-bottom"><a className="logo" href="#top">Rin LyHour<span>.</span></a><div><a href="mailto:rinlyhour9@gmail.com"><Mail size={16}/> Email</a><a href="https://t.me/LyyHourRinn" target="_blank" rel="noreferrer"><Send size={16}/> Telegram</a></div><span>© 2026 Rin LyHour</span></div></footer>
  </main>
}
createRoot(document.getElementById('root')).render(<App />)
